os:
  - linux

language: node_js

node_js:
  - "node"

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

before_install:
  - npm install -g yarn

install:
  - yarn install

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js